on: push
jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: shivammathur/setup-php@v2
          with:
            php-version: '8.3'
            coverage: xdebug
            tools: composer:v2

        - id: composer-cache
          run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

        - uses: actions/cache@v4
          with:
            path: ${{ steps.composer-cache.outputs.dir }}
            key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}

        - run: composer install --prefer-dist
        - run: vendor/bin/phpunit --colors test
        - run: vendor/bin/infection --test-framework=phpunit --show-mutations --min-msi=100 --threads=$(nproc)
